/**
 * 
 */
	$(function()
	{
	
		$(".page:eq(0)").mouseover(function()
		{
			$(".page:eq(0)").css({color:"#4d9900"});
		});
		$(".page:eq(1)").mouseover(function()
		{
			$(".page:eq(1)").css({color:"#4d9900"});
		});
		$(".page:eq(2)").mouseover(function()
		{
			$(".page:eq(2)").css({color:"#4d9900"});
		});
		$(".page:eq(3)").mouseover(function()
		{
			$(".page:eq(3)").css({color:"#4d9900"});
		});
		$(".page:eq(0)").mouseout(function()
		{
			$(".page:eq(0)").css({color:"white"});
		});
		$(".page:eq(1)").mouseout(function()
		{
			$(".page:eq(1)").css({color:"white"});
		});
		$(".page:eq(2)").mouseout(function()
		{
			$(".page:eq(2)").css({color:"white"});
		});
		$(".page:eq(3)").mouseout(function()
		{
			$(".page:eq(3)").css({color:"white"});
		});
		if(totalPage==currentPage)
		{
			$(".page:eq(2)").attr({href:"#"});
		}
		if(currentPage==1)
		{
			$(".page:eq(1)").attr({href:"#"});
		}
		
	});