/**
 * 
 */
$(function()
{
	$(".giveup").click(function()
	{
		window.location.href="/毕业设计/jsp/Main.jsp";
	});
	$(".combo").height(28);
	$(".combo-text").height(28);
	$(".num").focusout(function(){
		$.ajax({
			url:"/毕业设计/checkEntryEmployeeNum",
			data:{employeeNum:$(".num").val()},
			success:function(data)
			{
				/*alert(data);
				alert(typeof data);
				alert(data==="false");*/
				if(data===false)
				{
					alert("请输入正确的员工号");
					$(".num").focus();
				}
				else
				{
					$.ajax({
						url:"/毕业设计/getEmployeeName",//
						data:{employeeNum:$(".num").val()},
						success:function(data)
						{
							$(".name").val(data);
						}
					});
				}
			}
		});
	});
	$(".submit").click(function(){
		if($("input:eq(0)").val()!="" && $("input:eq(1)").val()!="" && $("input:eq(2)").val()!="" && $("input:eq(3)").val()!="" && $(".combo-value").val()!="" && $(".select:eq(0)").val()!="" && $(".select:eq(1)").val()!=""&& $(".select:eq(2)").val()!="" && $(".select:eq(3)").val()!="")
		{
			if(checkTime($(".combo-value").val()))
			{
				$("form").submit();
			}
			else
			{
				alert("日期必须是以前的");
			}
			
		}
		else
		{
			alert("请将信息填写完整");
		}
		
	});
	$(".select:eq(2)").change(function(){
		var select = document.getElementById("shi");
		for(var x=0;x<select.length;)
		{
			shi.remove(x);
		} 
		$.ajax({
			url:"/毕业设计/getDuty",
			data:{department:$(".select:eq(2)").val()},
			success:function(data)
			{
				for(i=0;i<data.length;i++)
				{
					var option = document.createElement("option");
					option.text = data[i];
					select.add(option,null);
				}
			}
		});
	});
	/*$("input:eq(1)").focusin(function()
	{
		if($("input:eq(0)").val()=="")
		{
			alert("不允许有空项！");	
		}
	});
	$("input:eq(2)").focusin(function()
	{
		if($("input:eq(1)").val()=="")
		{
			alert("不允许有空项！");	
		}
	});
	$("input:eq(3)").focusin(function()
			{
				if($("input:eq(2)").val()=="")
				{
					alert("不允许有空项！");	
				}
			});
	$("input:eq(4)").focusin(function()
			{
				if($("input:eq(3)").val()=="")
				{
					alert("不允许有空项！");	
				}
			});
	$("input:eq(5)").focusin(function()
			{
				if($("input:eq(4)").val()=="")
				{
					alert("不允许有空项！");	
				}
			});
	$("input:eq(6)").focusin(function()
			{
				if($("input:eq(5)").val()=="")
				{
					alert("不允许有空项！");	
				}
			});
	$("input:eq(7)").focusin(function()
			{
				if($("input:eq(6)").val()=="")
				{
					alert("不允许有空项！");	
				}
			});
	$("input:eq(8)").focusin(function()
			{
				if($("input:eq(7)").val()=="")
				{
					alert("不允许有空项！");	
				}
			});
	$("input:eq(9)").focusin(function()
			{
				if($("input:eq(8)").val()=="")
				{
					alert("不允许有空项！");	
				}
			});*/
});